moved a function to its correcor handling to fzf

diff --git a/aurroamer b/aurroamer
--- a/aurroamer
+++ b/aurroamer
@@ -29,11 +29,6 @@ touch "$favorites_file"
 touch "$ignore_file"
 
 mode=""
-
-require_binary fzf
-require_binary pacman
-require_binary curl
-require_binary gunzip
 	
 require_binary() {
    if ! command -v "$1" > /dev/null; then
@@ -41,6 +36,11 @@ require_binary() {
 	exit 1
    fi
 }
+
+require_binary fzf
+require_binary pacman
+require_binary curl
+require_binary gunzip
 
 cleanup() {
     rm -f "$aurpackages" "$repopackages" "$total"
@@ -275,7 +275,6 @@ if [[ "${1-}" == "--install" || "${1-}" == "-i" ]]; then
     fi
 fi
 
-fastmode=false
 if [[ "${1-}" == "--fast" || "${1-}" == "-f" ]]; then
     fastmode=true
     echo "fast mode: using cached package lists"
@@ -333,7 +332,10 @@ fi
 generate_fzf_input "$mode"
 echo
 while true; do
-    selection=$(echo "$fzf_input" | fzf --prompt="Search >> " --multi)
+    if ! selection=$(echo "$fzf_input" | fzf --prompt="Search >> " --multi); then
+    echo "fzf exited or failed"
+    exit 1
+fi
     [[ -z "$selection" ]] && exit 0
 
     mapfile -t selected_lines <<< "$selection"
